name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install dependencies
        run: nci

      - name: Build
        run: |
          mkdir -p all-dist
          
          for dir in talks/*/ ; do
            talk_name=$(basename "$dir")
            echo "🔧 Building $talk_name..."

            cd "$dir"
            npm install

            npx slidev build --base /${{ github.event.repository.name }}/talks/$talk_name/

            mkdir -p ../../all-dist/talks/$talk_name
            cp -r dist/* ../../all-dist/talks/$talk_name/

            cd ../../
          done

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
